### ISSUE TITLE
Export warning

### ISSUE THREAD

**Issue by phpd1992** [Dansteve/react-monnify#2]
Always getting this warning with this react package.
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by Dansteve** [comment]
The following issue has been fixed

Regards,
Dansteve.

Dansteve Adekanbi
danstevea@gmail.com
Business / Software Developer
m: +234 814 310 8254
